#!/bin/bash
failed=""
passed=""
for x in G_* ; do
  want_group="${x#G_}"
  got_group="$(../symmetry.x -verbose -1 "$x" | awk '/It seems to be the .* point group/{print $6}')"
  # echo "For the $want_group geometry I got $got_group"
  if [ "$want_group" != "$got_group" ] ; then
    failed="$failed $want_group"
  else
    passed="$passed $want_group"
  fi
done
[ -n "$passed" ] && echo "Tests passed: $passed"
if [ -n "$failed" ]; then
  echo "Tests failed: $failed"
  exit 1
fi
